import type { Metadata } from "next";
import { Fjalla_One, Cantarell } from "next/font/google";
import "./globals.css";

const FjallaOne = Fjalla_One({
  variable: "--font-fjalla-one",
  subsets: ["latin"],
  weight: '400',
});

const CantarellSans = Cantarell({
  variable: "--font-cantarell-sans",
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${FjallaOne.variable} ${CantarellSans.variable} antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
